// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGDELEGATE_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGDELEGATE_HPP_JNI_

#include "../../api/CosmosLikeMsgDelegate.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgDelegate final {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgDelegate;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgDelegate;

    ~CosmosLikeMsgDelegate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CosmosLikeMsgDelegate();
    friend ::djinni::JniClass<CosmosLikeMsgDelegate>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/CosmosLikeMsgDelegate") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGDELEGATE_HPP_JNI_
