// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#include "CosmosLikeMessage.hpp"  // my header
#include "CosmosLikeMsgDelegate.hpp"
#include "CosmosLikeMsgDeposit.hpp"
#include "CosmosLikeMsgRedelegate.hpp"
#include "CosmosLikeMsgSend.hpp"
#include "CosmosLikeMsgSubmitProposal.hpp"
#include "CosmosLikeMsgType.hpp"
#include "CosmosLikeMsgUndelegate.hpp"
#include "CosmosLikeMsgVote.hpp"
#include "CosmosLikeMsgWithdrawDelegationReward.hpp"

namespace djinni_generated {

CosmosLikeMessage::CosmosLikeMessage() : ::djinni::JniInterface<::ledger::core::api::CosmosLikeMessage, CosmosLikeMessage>("co/ledger/core/CosmosLikeMessage$CppProxy") {}

CosmosLikeMessage::~CosmosLikeMessage() = default;


CJNIEXPORT void JNICALL Java_co_ledger_core_CosmosLikeMessage_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ledger::core::api::CosmosLikeMessage>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_00024CppProxy_native_1getMessageType(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ledger::core::api::CosmosLikeMessage>(nativeRef);
        auto r = ref->getMessageType();
        return ::djinni::release(::djinni_generated::CosmosLikeMsgType::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgSend(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgSend(::djinni_generated::CosmosLikeMsgSend::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgSend(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgSend(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgSend::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgDelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgDelegate(::djinni_generated::CosmosLikeMsgDelegate::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgDelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgDelegate(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgDelegate::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgUndelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgUndelegate(::djinni_generated::CosmosLikeMsgUndelegate::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgUndelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgUndelegate(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgUndelegate::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgRedelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgRedelegate(::djinni_generated::CosmosLikeMsgRedelegate::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgRedelegate(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgRedelegate(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgRedelegate::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgSubmitProposal(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgSubmitProposal(::djinni_generated::CosmosLikeMsgSubmitProposal::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgSubmitProposal(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgSubmitProposal(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgSubmitProposal::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgVote(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgVote(::djinni_generated::CosmosLikeMsgVote::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgVote(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgVote(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgVote::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgDeposit(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgDeposit(::djinni_generated::CosmosLikeMsgDeposit::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgDeposit(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgDeposit(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgDeposit::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_wrapMsgWithdrawDelegationReward(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::wrapMsgWithdrawDelegationReward(::djinni_generated::CosmosLikeMsgWithdrawDelegationReward::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMessage::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_ledger_core_CosmosLikeMessage_unwrapMsgWithdrawDelegationReward(JNIEnv* jniEnv, jobject /*this*/, jobject j_msg)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ledger::core::api::CosmosLikeMessage::unwrapMsgWithdrawDelegationReward(::djinni_generated::CosmosLikeMessage::toCpp(jniEnv, j_msg));
        return ::djinni::release(::djinni_generated::CosmosLikeMsgWithdrawDelegationReward::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
