// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP_JNI_

#include "../../api/CosmosLikeMsgUndelegate.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgUndelegate final {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgUndelegate;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgUndelegate;

    ~CosmosLikeMsgUndelegate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CosmosLikeMsgUndelegate();
    friend ::djinni::JniClass<CosmosLikeMsgUndelegate>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/CosmosLikeMsgUndelegate") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP_JNI_
