// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGREDELEGATE_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGREDELEGATE_HPP_JNI_

#include "../../api/CosmosLikeMsgRedelegate.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgRedelegate final {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgRedelegate;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgRedelegate;

    ~CosmosLikeMsgRedelegate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CosmosLikeMsgRedelegate();
    friend ::djinni::JniClass<CosmosLikeMsgRedelegate>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/CosmosLikeMsgRedelegate") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGREDELEGATE_HPP_JNI_
