// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGSUBMITPROPOSAL_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGSUBMITPROPOSAL_HPP_JNI_

#include "../../api/CosmosLikeMsgSubmitProposal.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgSubmitProposal final {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgSubmitProposal;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgSubmitProposal;

    ~CosmosLikeMsgSubmitProposal();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CosmosLikeMsgSubmitProposal();
    friend ::djinni::JniClass<CosmosLikeMsgSubmitProposal>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/CosmosLikeMsgSubmitProposal") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGSUBMITPROPOSAL_HPP_JNI_
